### ISSUE TITLE
is this a bug "bcP.value.toInt"

### ISSUE THREAD

**Issue by yahu** [data61/stellar-random-walk#1]
at RandomWalk.scala:83
` val (nextStep, _) = rSample.secondOrderSample(bcP.value.toInt, bcQ.value.toInt, prev, pNeighbors, currNeighbors)`

by definition `secondOrderSample(p: Float = 1.0f,
                              q: Float = 1.0f,
                              prevId: Int,
                              prevNeighbors: Array[(Int, Float)],
                              currNeighbors: Array[(Int, Float)])`
p and q should be double

**Comment by shps** [comment]
Hi Yue,

Thanks for the bug report. Yes, that is a bug and I will fix it soon.

Cheers,
Hooman
